language: php
php:
- 5.5
- 5.6
install:
- composer install
- npm install
script:
- ./vendor/bin/phing test
after_success:
- ./vendor/bin/coveralls -vvv
notifications:
  email:
    recipients:
    - bert@2dotstwice.be
    - sander@2dotstwice.be
    - kristof@2dotstwice.be
