cors:
  origins: []
debug: true
uitid:
  consumer:
    key: ***
    secret: ***
  base_url: http://www.uitid.be/uitid/rest/
search:
  base_url: http://www.uitid.be/uitid/rest/searchv2
swiftmailer.options:
  # This connects to a mailserver at port 1025
  # This is not the standard SMTP port, but the default port of Mailcatcher,
  # a great tool for debugging mail. Check it out! http://mailcatcher.me/
  host: 127.0.0.1
  port: 1025
feedback:
  from: noreply@uitid.be
  to: info@uitpas.be
  subject: "UiTPAS balie beheer feedback."
httpclient:
  timeout: 30
bootstrap:
  logging: false
roles:
  Default2d2:
  - ROLE_HELP_EDIT
export:
  limit_per_api_request: 50
